### PR TITLE
James/crash fix

### PR DESCRIPTION
**Pull request by jallen-NextDroid**
I tagged anyone who might be interested as a reviewer. This fixes the crashes and lag related to control points. Potree runs at a consistent 55-60 FPS with this fix.

### CODE REVIEW

**Comment by jallen-NextDroid** [comment]
Basically, the lag was caused by way too many control points in the scene, even if they weren't visible. So instead of loading every control point to the scene, I'm loading a single control point and simply changes its position and timestamps

**Comment by bcasselsND** [comment]
What happens if the user zooms out, and everything is visible?

Potential solutions if there are too many:
- Don't show any. Assume you're too zoomed out to see anything, anyway.
- Show a limited number. Choose heuristically?
  - Every nth one
  - Don't show if there's another "nearby", where distance is chosen heuristically
- Other ideas??

**Comment by bcasselsND** [comment]
Oh, right. Where I said "zoom" above, I meant "expanding the time window".

So @nmhaddadND, while you're thinking about fixing the time window, let's figure out how to handle too many points.

**Comment by jallen-NextDroid** [comment]
So I've spent the whole day trying to find the best way to optimize this. I tried breaking the huge sphereMeshes array into chunks by timestamp for example, but didn't see any noticeable improvement with anything I tried. As it stands, crashing is fixed and it runs at 60 FPS, but drops to 20-30 every few seconds causing a stutter. Definitely still an improvement, and I think we should merge this asap so that potree at least works. Then we can move onto optimization.

**Pull request merged**
