### PR TITLE
[feat] Label Cuboids & Download Labels

### LINKED ISSUE #147: Data Labeling & Cuboids
## Current Work

- initial work done by @bcasselsND on branch `bcassels/cuboids`
- labeling works, but not in `radar.html` (just in `http://localhost:1234/data-labeling/data-labeling.html`)
- creates list of label json:
``` json
{
  "t_valid_min": 0,
  "t_valid_max": null,
  "timestamp": 1591395173388,
  "position": {
    "x": -0.061213016510009766,
    "y": -2.4204059839248653,
    "z": 4.487650059525813
  },
  "rotation": {
    "_x": 0,
    "_y": 0,
    "_z": 0,
    "_order": "XYZ"
  },
  "size": {
    "x": 1.50917380887355,
    "y": 1.50917380887355,
    "z": 2.6362620320941543
  },
  "label": "non_road",
  "metadata": "My metadata"
}
``` 

## To Do

- [x] Refactor and link labeling code to `radar.html` (only works on special page right now)
- [x] Rename "Label and Download" to just "Label" (only `export` button should download)
- [x] Have `export` button download list of labels
    - [x] Append label data to list 
    - [x] Parse list and filter out unlabeled cuboids
- [x] Remove redundant/obsolete popup titled `Label Bounding Box`  

## Steps to Use

1. open left hand "hamburger" menu
2. scroll down to `Clipping` -> `volume clip` -> Select Area
3. scroll down to `Properties` -> `Label`

### PR DESCRIPTION
**Pull request by NickRizzo-droid**
- closes #147 
- stops tracking `.vscode` folder
- `Label` Button
    - dropdown options appear for classification (see below)
    - click button again or select one of the options to hide dropdown
- `Preview` Button
     - Shows current label data through an alert
- `Export` Button
     - Downloads label data to you downloads folder
     - Contains what `Preview` shows
     - `Confirm` bubble asks if you are sure you want to download

## Volume Panel
(added dynamically after `Clipping` -> `Volume Clipping` is used once)

image

## Label Button
image

## Preview Button
image
- `Ok` progresses to next label
- `Cancel` stops previewing

## Download Confirmation Button
image

## Sample Exported Label
``` json
[
  {
    "t_valid_min": 1166920167.18,
    "t_valid_max": 1166920167.28,
    "timestamp": 1592414742018,
    "position": {
      "x": 598531.3912254459,
      "y": 4474495.491616728,
      "z": 348.25788801220835
    },
    "rotation": {
      "_x": 0,
      "_y": 0,
      "_z": 0,
      "_order": "XYZ"
    },
    "size": {
      "x": 7.374915804108605,
      "y": 7.374915804108605,
      "z": 7.374915804108605
    },
    "label": "road",
    "metadata": "test1-start"
  },
  {
    "t_valid_min": 1166920167.18,
    "t_valid_max": 1166920167.28,
    "timestamp": 1592414766192,
    "position": {
      "x": 598533.8953674197,
      "y": 4474511.185328973,
      "z": 347.3846004646722
    },
    "rotation": {
      "_x": 0,
      "_y": 0,
      "_z": 0,
      "_order": "XYZ"
    },
    "size": {
      "x": 8.817374340677635,
      "y": 8.817374340677635,
      "z": 8.817374340677635
    },
    "label": "road",
    "metadata": "test2- lane merge"
  }
]
```

### CODE REVIEW

**Comment by bcasselsND** [comment]
I don't see a need for preview. The export button should be with these, and look similar. Maybe with a header "Labels:" with JSON underneath. It should only appear when there are labeled cuboids. (So it doesn't confuse customers who aren't using this feature.)
Screen Shot 2020-06-17 at 1 42 00 PM

**Comment by bcasselsND** [comment]
No need for download confirmation. Just do it.

Ultimately, the labeled cuboids will probably go somewhere else...

**Comment by NickRizzo-droid** [comment]
> I don't see a need for preview.

Maybe it would be useful to see the cuboid information without having to actually download it? Any opinions @arjunskND ?

**Comment by NickRizzo-droid** [comment]
> The export button should be with these, and look similar. Maybe with a header "Labels:" with JSON underneath. It should only appear when there are labeled cuboids. (So it doesn't confuse customers who aren't using this feature.)

Understood, I'll do this

**Comment by NickRizzo-droid** [comment]
This download location and button look likes this now:
(it only appears after `Label` has been clicked once)

image

**Comment by arjunskND** [comment]
I'm about to play around with this with @SantoshReddyND now

**Pull request merged**
